config/routes.rb
Rails.application.routes.draw do
  resources :listings

  devise_for :users
  
  get '/button', to: 'listings#button', as: 'button'

  root to: 'listings#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  belongs_to :state

  validates :suburb, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true
  validates :unit_address, :postal_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/console.rb
class Console < ApplicationRecord
    # database relationships
    has_many :listings

    # validates the attribute with different requirements
    validates :console_type, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  # database relationships
  belongs_to :user
  belongs_to :console
  has_one_attached :picture, dependent: :destroy

  # validates the attributes with different requirements
  validates :listing_title, length: { in: 10..100, message: "should be within 10 to 100 characters"}, presence: true
  validates :description, length: { in: 20..5000, message: "should be within 20 to 5000 characters" }, presence: true
  validates :price, :picture, presence: true

  # Search scope that set up the searching target
  scope :search_by_listing_title, -> (listing_title) {where('listing_title ILIKE ?', "%#{listing_title}%")}
  scope :filter_by_console, -> (id) {where(console_id: id)}

  # Search method
  def self.search(search_hash)
    if search_hash
      Listing.search_by_listing_title(search_hash["listing_title"]).filter_by_console(search_hash["console_id"])
    else
      Listing.all
    end
  end
end

app/models/state.rb
class State < ApplicationRecord
    # database relationships
    has_many :addresses

    # validates the attribute with different requirements
    validates :state_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  # validates the attributes with different requirements
  validates :phone_number, numericality: { only_integer: true, message: "only allows integers"}, length: { is: 9, message: "require 9 digits" }, presence: true
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }, presence: true

  # database relationships
  has_many :listings, dependent: :destroy
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  def with_address
    build_address if address.nil?
    self
  end

  # gem "Pundit" logic 
  def admin?; false; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Pundit which shows error message or rescues unauthorized action in MVC model
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
      flash[:alert] = "This is not your listing. You are not authorized to perform edit/delete."
      redirect_to root_path
    end

    # Devise which permits strong parameters in MVC model
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, address_attributes: [:unit_address, :suburb, :postal_code, :state_id]])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number, address_attributes: [:unit_address, :suburb, :postal_code, :state_id]])
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    # Authenicate the user before directing to the pages under these actions "new/create/show/edit/update/destroy"
    before_action :authenticate_user!, only: %i[new create show edit update destroy]
    # show a listing with the corresponding listing_id before directing to the pages under these actions "show/edit/update/destroy"
    before_action :set_listing, only: %i[show edit update destroy]
    
    # Shows all the created listing in the index page
    # Minimize database calls on listing model
    # @consoles is for search function that pass the instance variable to index view
    def index
        @listings = Listing.search(params[:search]).includes(:console, :user, picture_attachment: :blob, user: :address, user: [address:[:state]])
        @consoles = Console.all
    end

    # Shows only 1 created listing in the show page
    def show
    end
    
    # Create a new instance variable for Listing
    def new
        @listing = Listing.new
    end

    # Call the instance variable from action "new"
    # Verify there is a user before creating a new listing 
    def create
        @listing = current_user.listings.new(permitted_params)
        # If the created listing successfully saved/created, redirect to the show page/ newly created listing page
        if @listing.save
            redirect_to @listing
        else
            # render the create / new page
            render :new
        end
    end

    def edit
        # Authoization where only the listing creator can edit the listing
        authorize @listing
    end

    def update
        # Authoization where only the listing creator can update the listing
        authorize @listing

        # If the created listing successfully updated, redirect to the show page/ updated listing page
        if @listing.update(permitted_params)
            redirect_to @listing
        else
             # render the edit page
            render :edit
        end
    end

    def destroy
        # Authoization where only the listing creator can delete the listing
        authorize @listing

        # Destroy the listing after a notice appears to check whether the user confirm to delete the listing
        @listing.destroy
            redirect_to listings_path, notice: 'Listing was successfully deleted.'
    end

private

    # Allow model attributes for mass update towards the database where only stated strong parameters are permitted
    def permitted_params
        params.required(:listing).permit(:listing_title, :description, :price, :console_id, :user_id, :picture) 
    end

    # show a listing with the corresponding listing_id
    def set_listing
        @listing = Listing.find(params[:id])
    end

end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController


    def index
        @posts = Post.all
    end

# Shows only 1 created post of selling a second-hand game
    def show

    end
    
    def new
        @post = Post.new
    end

    def create
        @post = Post.new permitted_params
        if @post.save
            redirect_to index
        else
            render :new
        end
    end

private

    def permitted_params
        params.required(:post).permit(:listing_title, :description, :price) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="/assets/icon.png" type="image/x-icon" sizes="16x16"/>
  </head>

  <body class="background">
      <p class="notice"><%= notice %></p> <%# devise notice %>
      <p class="alert"><%= alert %></p> <%# devise alert %>
      <%= render "shared/navbar" %> <%# render the partial file _navbar.html.erb from shared folders %>
      <%= render "shared/heading" %> <%# render the partial file _heading.html.erb from shared folders %>
      <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<h1 class="heading">Edit Listing</h1>

<%# render the partial file _listing_form.html.erb from shared folders %>
<%# Assign the variables here so it can understand the variables in the form %>
<%= render "shared/listing_form", listing: @listing %>

app/views/listings/index.html.erb
<%# Ruby iterators returning the specific elements of seller listings %>

<%# Display the search function that allow users to input text or select console and search%>
<div class="search-box">
    <%= form_with(method:'get', url: listings_path, scope: :search, local: true) do |f| %>
        <%=f.label :listing_title%>:
        <%=f.text_field :listing_title %>

        <%=f.label :console_id%>:
        <%=f.select :console_id, @consoles.map {|c| [c.console_type, c.id]} %>

        <%= f.submit "Search" %>
    <% end %>
</div>

<% @listings.each do |l| %>
    <%# flexbox to manage the alignment and position of the inner flexbox%>
    <main class="index-outer-box">

        <%# flexbox contains image %>
        <section class="index-inner-box1">
            <%# using Ruby to check whether a picture is uploaded or not %>
            <%= image_tag l.picture, class: "image" if l.picture.attached? %>
        </section>

        <%# flexbox contains listing title, console type, and description %>
        <section class="index-inner-box2">
            <%# using Ruby to bring up listing title created by users from database %>
            <h4><%= link_to "#{l.listing_title}", l %></h4>
            <%# using Ruby to bring up console type chosen by users from database %>
            <p>
                Console: <strong><u><%= l.console.console_type %></u></strong>
            </p>
            <%# using Ruby to bring up description created by users from database %>
            <p>
                <%= l.description %>
            </p>
        </section>

        <%# flexbox contains seller's name, subrub, state, and listing time %>
        <section class="index-inner-box3">
            <%# using Ruby to bring up price set by users from database %>
            <p>
                Price: <strong><u>$<%= l.price %></u></strong>
            </p>
            <%# using Ruby to bring up user first and last name from database %>
            <p>
                <%= l.user.first_name.capitalize%> <%= l.user.last_name.capitalize%>
            </p>
            <%# using Ruby to bring up user suburb and state from database %>
            <p>
                <%= l.user.address.suburb.capitalize%>, <%= l.user.address.state.state_name%>
            </p>
            <br>
            <span>Last Update:</span>
            <%# using Ruby to bring up listing last update time from database %>
            <span><%= l.updated_at.strftime("%B %d, %Y") %><span><br>
        </section>

    </main>
<% end %>


app/views/listings/new.html.erb
<h1 class="heading">Create a New Listing </h1>

<%# render the partial file _listing_form.html.erb from shared folders %>
<%# Assign the variables here so it can understand the variables in the form %>
<%= render "shared/listing_form", listing: @listing %>

app/views/listings/show.html.erb
<%# Picture conatains in a flexbox %>
<%# Display the picture if there is any %>
<div class="show-image-box">
    <%= image_tag @listing.picture, class: "image" if @listing.picture.attached? %><br>
</div>

<section class="show-form">
    <%# Display listing title %>
    <div>
        <h4><u><%= @listing.listing_title %></u></h4>
    </div>

    <%# Display listing console type %>
    <div>
        Console: <strong><%= @listing.console.console_type %></strong>
    </div><br>

    <%# Display listing description %>
    <div>
        <%= @listing.description %>
    </div><br>

    <%# Display listing price %>
    <div>
        Price: <strong>$<%= @listing.price %></strong>
    </div><br>

    <%# Display listing creator's first and last name %>
    <div>
        Seller Name: <strong><%= @listing.user.first_name.capitalize%> <%= @listing.user.last_name.capitalize%></strong>
    </div><br>

    <%# Display listing creator's phone number %>
    <div>
        Phone Number: <strong>+61 <%= @listing.user.phone_number%></strong>
    </div><br>

    <%# Display listing creator's email%>
    <div>
        Email: <strong><%= @listing.user.email%></strong>
    </div><br>

    <%# Display listing creator's suburb %>
    <div>
        Suburb: <strong><%= @listing.user.address.suburb.capitalize%></strong>
    </div><br>

    <%# Display listing creator's state %>
    <div>
        State: <strong><%= @listing.user.address.state.state_name%></strong>
    </div><br>

    <%# Display listing last update date%>
    <div>
        Last Update: <%= @listing.updated_at.strftime("%B %d, %Y") %>
    </div><br>

    <%# Authorize only the listing creator to edit or delete the listing %>
    <div>
        <% if policy(@listing).update? %>
            <%= button_to 'Edit', edit_listing_path(@listing), method: :get, form_class: "edit-delete" %>
            <%= button_to 'Delete', @listing, method: :delete, data: { confirm: 'Do you confirm to delete the listing?' }, form_class: "edit-delete"%>
        <% end %>
    </div>
</section>

app/views/shared/_heading.html.erb
<%# This is a partial of heading where each pages of the app contains the heading and it links to the index/home page%>
<section>  
    <h1 class= "heading"><%= link_to "GameHub", listings_path %></h1>
</section>

app/views/shared/_listing_form.html.erb
<%# call the instance variable @listing from either new.html.erb or edit.html.erb %>
<%= form_with model: listing do |form| %>
    <%# If there is any error, error messages are show for each error %>
    <% if listing.errors.any? %>
        <div>
            <h2><%= pluralize(listing.errors.count, "error") %> occured. Please follow the requirements below:</h2>
            <ul>
                <% listing.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <section class="new-form">
        <%# Using form to display listing title input field %>
        <div>
            <%= form.label :listing_title %>:
            <%= form.text_field :listing_title %>
        </div><br>

        <%# Using collection select to select a console type%>
        <div>
            <%= form.label :console_id %>:
            <%= form.collection_select :console_id, Console.all, :id, :console_type %>
        </div><br>

        <%# Using form to display description input field %>
        <div>
            <%= form.label :description %>:<br>
            <%= form.text_area :description, size: "70x10" %>
        </div><br>

        <%# Using form to display price input field %>
        <div>
            <%= form.label :price %>: $
            <%= form.number_field :price, min: 0, max: 1000 %>
        </div><br>

        <%# Provide a file upload button for picture upload%>
        <div>
            <%= form.label :picture %>:
            <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg' %>
        </div><br>

        <%# submit button %>
        <div> 
            <%= form.submit %>
        </div>
    </section>

<% end %>


app/views/shared/_navbar.html.erb
<%# A welcome message that shows the user is logged in %>
<p class="welcome">    
    <% if user_signed_in? %>
            <%= "Welcome, #{current_user.first_name}!"%> 
    <% end %>
</p>

<%# A navbar with conditional statements. If the user is signed-in, the navbar will show Create, Edit Profile, 
and Sign Out. If the user is not signed-in, the navbar will show Create, Register, and Sign In. %>
<nav class="navbar">
    <% if user_signed_in? %>
        <span><%= link_to "Create", new_listing_path %></span>
        <span><%= link_to "Edit Profile", edit_user_registration_path %></span>
        <span><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></span>
    <% else %>
        <span><%= link_to "Create", new_listing_path %></span>
        <span><%= link_to "Register", new_user_registration_path %></span>
        <span><%= link_to "Sign In", new_user_session_path %></span>
    <% end %>
</nav>

app/views/shared/_post_form.html.erb
<%= form_with model: @post do |form| %>
    <div class="field">
        <%= form.label :listing_title %>:
        <%= form.text_field :listing_title %>
    </div><br>

    <div class="field">
        <%= form_for @post do |f| %>
            <%= form.label :console %>:
            <%= f.select :console_id, Console.all.collect { |p| [ p.console_type] }%>
        <% end %>
    </div><br>

    <div class="field">
        <%= form.label :description %>:<br>
        <%= form.text_area :description, size: "70x5" %>
    </div><br>

    <div class="field">
        <%= form.label :price %>:
        <%= form.number_field :price, min: 0, max: 1000 %>
    </div><br>

    <div class="action">
        <%= form.submit %>
    </div>
<% end %>
